# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.cache/wt [current_project]
set_property parent.project_path C:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_repo_paths c:/Users/Dbr/Documents/Vivado/LAGO/ip_repo [current_project]
set_property ip_output_repo c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/imports/sources/spi_master.vhd
  C:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/imports/sources/DAC_CTRL1v1.vhd
  C:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/imports/timestamp/FIFO_MGR/FIFOMGR.VHD
  C:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/imports/timestamp/mstrigger/array_pkg.vhd
  C:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/imports/timestamp/mstrigger/Trigger.vhd
  C:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/imports/timestamp/mstrigger/diff_checker.vhd
  C:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/imports/timestamp/mstrigger/mstrigger.vhd
  C:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/imports/timestamp/Timestamp_Sources/timer.vhd
  C:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/imports/timestamp/Timestamp_Sources/stamp.vhd
  C:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/imports/timestamp/Timestamp_Sources/timestamp.vhd
  C:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/imports/sources/reg_fmc_adc_ctrl.vhd
  C:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/new/GPS_EN.vhd
  C:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/hdl/design_2_wrapper.vhd
}
read_ip -quiet C:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/ip/c_shift_ram_0/c_shift_ram_0.xci

add_files C:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/design_2.bd
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_proc_sys_reset_1_0/design_2_proc_sys_reset_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_proc_sys_reset_1_0/design_2_proc_sys_reset_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_util_ds_buf_0_1/design_2_util_ds_buf_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_util_ds_buf_0_1/design_2_util_ds_buf_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_util_ds_buf_0_1/design_2_util_ds_buf_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_util_ds_buf_1_0/design_2_util_ds_buf_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_util_ds_buf_1_0/design_2_util_ds_buf_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_util_ds_buf_1_0/design_2_util_ds_buf_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_proc_sys_reset_0_0/design_2_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_proc_sys_reset_0_0/design_2_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_processing_system7_0_0/design_2_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_Hist_Gen_Block_0_0/src/osc_XDC.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_Hist_Gen_Block_0_0/src/Histo1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_OLD_fifo_0/design_2_OLD_fifo_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_OLD_fifo_0/design_2_OLD_fifo_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_axi_dma_0_0/design_2_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_axi_dma_0_0/design_2_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_axi_dma_0_0/design_2_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_7/bd_ebcc_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_11/bd_ebcc_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_8/bd_ebcc_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_9/bd_ebcc_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_10/bd_ebcc_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_1/bd_ebcc_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_1/bd_ebcc_psr0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_2/bd_ebcc_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_2/bd_ebcc_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_3/bd_ebcc_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_3/bd_ebcc_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_clk_wiz_0_0/design_2_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_clk_wiz_0_0/design_2_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_clk_wiz_0_0/design_2_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_util_ds_buf_0_0/design_2_util_ds_buf_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_util_ds_buf_0_0/design_2_util_ds_buf_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_util_ds_buf_0_0/design_2_util_ds_buf_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_util_ds_buf_2_0/design_2_util_ds_buf_2_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_util_ds_buf_2_0/design_2_util_ds_buf_2_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_util_ds_buf_2_0/design_2_util_ds_buf_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_util_ds_buf_3_0/design_2_util_ds_buf_3_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_util_ds_buf_3_0/design_2_util_ds_buf_3_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_util_ds_buf_3_0/design_2_util_ds_buf_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_axi_uartlite_0_0/design_2_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_axi_uartlite_0_0/design_2_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_axi_uartlite_0_0/design_2_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_axi_gpio_0_0/design_2_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_axi_gpio_0_0/design_2_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_axi_gpio_0_0/design_2_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_clk_wiz_0_1/design_2_clk_wiz_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_clk_wiz_0_1/design_2_clk_wiz_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_clk_wiz_0_1/design_2_clk_wiz_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_auto_pc_4/design_2_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_auto_pc_3/design_2_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_auto_pc_2/design_2_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_auto_pc_1/design_2_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_auto_pc_0/design_2_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_auto_pc_5/design_2_auto_pc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/sources_1/bd/design_2/design_2_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/constrs_1/imports/constr/Sensors.xdc
set_property used_in_implementation false [get_files C:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/constrs_1/imports/constr/Sensors.xdc]

read_xdc C:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/constrs_1/imports/constr/osc_XDC.xdc
set_property used_in_implementation false [get_files C:/Users/Dbr/Documents/Vivado/LAGO/LAGO_ICTP/LAGO_ICTP.srcs/constrs_1/imports/constr/osc_XDC.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top design_2_wrapper -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_2_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_2_wrapper_utilization_synth.rpt -pb design_2_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
