# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constr/Sensors.xdc

# XDC: imports/constr/osc_XDC.xdc

# IP: ip/c_shift_ram_0/c_shift_ram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_shift_ram_0 || ORIG_REF_NAME==c_shift_ram_0} -quiet] -quiet

# Block Designs: bd/design_2/design_2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_comblock_0_0/design_2_comblock_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_comblock_0_0 || ORIG_REF_NAME==design_2_comblock_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_proc_sys_reset_1_0/design_2_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_proc_sys_reset_1_0 || ORIG_REF_NAME==design_2_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_util_ds_buf_0_1/design_2_util_ds_buf_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_util_ds_buf_0_1 || ORIG_REF_NAME==design_2_util_ds_buf_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_util_ds_buf_1_0/design_2_util_ds_buf_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_util_ds_buf_1_0 || ORIG_REF_NAME==design_2_util_ds_buf_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_proc_sys_reset_0_0/design_2_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_proc_sys_reset_0_0 || ORIG_REF_NAME==design_2_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_processing_system7_0_0/design_2_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_processing_system7_0_0 || ORIG_REF_NAME==design_2_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_processing_system7_0_axi_periph_0/design_2_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==design_2_processing_system7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xbar_0/design_2_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xbar_0 || ORIG_REF_NAME==design_2_xbar_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ADC_Decimator_0_0/design_2_ADC_Decimator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_ADC_Decimator_0_0 || ORIG_REF_NAME==design_2_ADC_Decimator_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_DAC_CTRL1v1_0_0/design_2_DAC_CTRL1v1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_DAC_CTRL1v1_0_0 || ORIG_REF_NAME==design_2_DAC_CTRL1v1_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Hist_Gen_Block_0_0/design_2_Hist_Gen_Block_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_Hist_Gen_Block_0_0 || ORIG_REF_NAME==design_2_Hist_Gen_Block_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Hist_Gen_Block_0_0/src/Histo1_histo_counter_0_0/Histo1_histo_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Histo1_histo_counter_0_0 || ORIG_REF_NAME==Histo1_histo_counter_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Hist_Gen_Block_0_0/src/Histo1_xlslice_0_0/Histo1_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Histo1_xlslice_0_0 || ORIG_REF_NAME==Histo1_xlslice_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Hist_Gen_Block_0_0/src/Histo1_xlslice_0_1/Histo1_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Histo1_xlslice_0_1 || ORIG_REF_NAME==Histo1_xlslice_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Hist_Gen_Block_0_0/src/Histo1_reg_bit_1_0/Histo1_reg_bit_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Histo1_reg_bit_1_0 || ORIG_REF_NAME==Histo1_reg_bit_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Hist_Gen_Block_0_0/src/Histo1_SBRAM_wen_mgr_0_0/Histo1_SBRAM_wen_mgr_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Histo1_SBRAM_wen_mgr_0_0 || ORIG_REF_NAME==Histo1_SBRAM_wen_mgr_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_FIFOMGR_0_0/design_2_FIFOMGR_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_FIFOMGR_0_0 || ORIG_REF_NAME==design_2_FIFOMGR_0_0} -quiet] -quiet

# IP: ip/c_shift_ram_0/c_shift_ram_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_shift_ram_0 || ORIG_REF_NAME==c_shift_ram_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ctrl_reg_0/design_2_ctrl_reg_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_ctrl_reg_0 || ORIG_REF_NAME==design_2_ctrl_reg_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ctrl_reg1_0/design_2_ctrl_reg1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_ctrl_reg1_0 || ORIG_REF_NAME==design_2_ctrl_reg1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ctrl_reg2_0/design_2_ctrl_reg2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_ctrl_reg2_0 || ORIG_REF_NAME==design_2_ctrl_reg2_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_mstrigger_0_0/design_2_mstrigger_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_mstrigger_0_0 || ORIG_REF_NAME==design_2_mstrigger_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_timer_0_0/design_2_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_timer_0_0 || ORIG_REF_NAME==design_2_timer_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_timestamp_1_0/design_2_timestamp_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_timestamp_1_0 || ORIG_REF_NAME==design_2_timestamp_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlconcat_0_1/design_2_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlconcat_0_1 || ORIG_REF_NAME==design_2_xlconcat_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlconcat_1_0/design_2_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlconcat_1_0 || ORIG_REF_NAME==design_2_xlconcat_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_AXI_Trigger_gen_m4_0_0/design_2_AXI_Trigger_gen_m4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_AXI_Trigger_gen_m4_0_0 || ORIG_REF_NAME==design_2_AXI_Trigger_gen_m4_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_FIFO_SIZE_0/design_2_FIFO_SIZE_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_FIFO_SIZE_0 || ORIG_REF_NAME==design_2_FIFO_SIZE_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_OLD_fifo_0/design_2_OLD_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_OLD_fifo_0 || ORIG_REF_NAME==design_2_OLD_fifo_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_dma_0_0/design_2_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_axi_dma_0_0 || ORIG_REF_NAME==design_2_axi_dma_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_smc_0/design_2_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_axi_smc_0 || ORIG_REF_NAME==design_2_axi_smc_0} -quiet] -quiet

# Block Designs: bd/design_2/ip/design_2_axi_smc_0/bd_0/bd_ebcc.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_7/bd_ebcc_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_11/bd_ebcc_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_12/bd_ebcc_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_8/bd_ebcc_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_9/bd_ebcc_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_10/bd_ebcc_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_4/bd_ebcc_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_5/bd_ebcc_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_6/bd_ebcc_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_0/bd_ebcc_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_1/bd_ebcc_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_2/bd_ebcc_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_3/bd_ebcc_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_empty_0/design_2_empty_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_empty_0 || ORIG_REF_NAME==design_2_empty_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_full_0/design_2_full_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_full_0 || ORIG_REF_NAME==design_2_full_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_tlast_gen_0_0/design_2_tlast_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_tlast_gen_0_0 || ORIG_REF_NAME==design_2_tlast_gen_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlconcat_0_0/design_2_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlconcat_0_0 || ORIG_REF_NAME==design_2_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlconstant_0_0/design_2_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlconstant_0_0 || ORIG_REF_NAME==design_2_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlconstant_1_0/design_2_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlconstant_1_0 || ORIG_REF_NAME==design_2_xlconstant_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_adc_controller_0_0/design_2_adc_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_adc_controller_0_0 || ORIG_REF_NAME==design_2_adc_controller_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_clk_wiz_0_0/design_2_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_0_0 || ORIG_REF_NAME==design_2_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_util_ds_buf_0_0/design_2_util_ds_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_util_ds_buf_0_0 || ORIG_REF_NAME==design_2_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_util_ds_buf_2_0/design_2_util_ds_buf_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_util_ds_buf_2_0 || ORIG_REF_NAME==design_2_util_ds_buf_2_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_util_ds_buf_3_0/design_2_util_ds_buf_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_util_ds_buf_3_0 || ORIG_REF_NAME==design_2_util_ds_buf_3_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_uartlite_0_0/design_2_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_axi_uartlite_0_0 || ORIG_REF_NAME==design_2_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_gpio_0_0/design_2_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_axi_gpio_0_0 || ORIG_REF_NAME==design_2_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_GPS_EN_0_0/design_2_GPS_EN_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_GPS_EN_0_0 || ORIG_REF_NAME==design_2_GPS_EN_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_clk_wiz_0_1/design_2_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_0_1 || ORIG_REF_NAME==design_2_clk_wiz_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_auto_pc_4/design_2_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_auto_pc_4 || ORIG_REF_NAME==design_2_auto_pc_4} -quiet] -quiet

# IP: bd/design_2/ip/design_2_auto_pc_3/design_2_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_auto_pc_3 || ORIG_REF_NAME==design_2_auto_pc_3} -quiet] -quiet

# IP: bd/design_2/ip/design_2_auto_pc_2/design_2_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_auto_pc_2 || ORIG_REF_NAME==design_2_auto_pc_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_auto_pc_1/design_2_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_auto_pc_1 || ORIG_REF_NAME==design_2_auto_pc_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_auto_pc_0/design_2_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_auto_pc_0 || ORIG_REF_NAME==design_2_auto_pc_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_auto_pc_5/design_2_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_auto_pc_5 || ORIG_REF_NAME==design_2_auto_pc_5} -quiet] -quiet

# XDC: bd/design_2/ip/design_2_proc_sys_reset_1_0/design_2_proc_sys_reset_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_proc_sys_reset_1_0 || ORIG_REF_NAME==design_2_proc_sys_reset_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_proc_sys_reset_1_0/design_2_proc_sys_reset_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_proc_sys_reset_1_0 || ORIG_REF_NAME==design_2_proc_sys_reset_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_util_ds_buf_0_1/design_2_util_ds_buf_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_util_ds_buf_0_1 || ORIG_REF_NAME==design_2_util_ds_buf_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_util_ds_buf_0_1/design_2_util_ds_buf_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_util_ds_buf_0_1 || ORIG_REF_NAME==design_2_util_ds_buf_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_util_ds_buf_0_1/design_2_util_ds_buf_0_1_ooc.xdc

# XDC: bd/design_2/ip/design_2_util_ds_buf_1_0/design_2_util_ds_buf_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_util_ds_buf_1_0 || ORIG_REF_NAME==design_2_util_ds_buf_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_util_ds_buf_1_0/design_2_util_ds_buf_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_util_ds_buf_1_0 || ORIG_REF_NAME==design_2_util_ds_buf_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_util_ds_buf_1_0/design_2_util_ds_buf_1_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_proc_sys_reset_0_0/design_2_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_proc_sys_reset_0_0 || ORIG_REF_NAME==design_2_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_proc_sys_reset_0_0/design_2_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_proc_sys_reset_0_0 || ORIG_REF_NAME==design_2_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_processing_system7_0_0/design_2_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_processing_system7_0_0 || ORIG_REF_NAME==design_2_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_Hist_Gen_Block_0_0/src/osc_XDC.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_Hist_Gen_Block_0_0 || ORIG_REF_NAME==design_2_Hist_Gen_Block_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_Hist_Gen_Block_0_0/src/Histo1_ooc.xdc

# XDC: bd/design_2/ip/design_2_OLD_fifo_0/design_2_OLD_fifo_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_OLD_fifo_0 || ORIG_REF_NAME==design_2_OLD_fifo_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_OLD_fifo_0/design_2_OLD_fifo_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_OLD_fifo_0 || ORIG_REF_NAME==design_2_OLD_fifo_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_axi_dma_0_0/design_2_axi_dma_0_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_dma_0_0/design_2_axi_dma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_axi_dma_0_0 || ORIG_REF_NAME==design_2_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_axi_dma_0_0/design_2_axi_dma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_axi_dma_0_0 || ORIG_REF_NAME==design_2_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_7/bd_ebcc_s00a2s_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_11/bd_ebcc_m00s2a_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_8/bd_ebcc_sawn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_9/bd_ebcc_swn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_10/bd_ebcc_sbn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_1/bd_ebcc_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_1/bd_ebcc_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_2/bd_ebcc_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_2/bd_ebcc_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_3/bd_ebcc_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_3/bd_ebcc_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/design_2/ip/design_2_axi_smc_0/ooc.xdc

# XDC: bd/design_2/ip/design_2_clk_wiz_0_0/design_2_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_0_0 || ORIG_REF_NAME==design_2_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_clk_wiz_0_0/design_2_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_0_0 || ORIG_REF_NAME==design_2_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_clk_wiz_0_0/design_2_clk_wiz_0_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_util_ds_buf_0_0/design_2_util_ds_buf_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_util_ds_buf_0_0 || ORIG_REF_NAME==design_2_util_ds_buf_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_util_ds_buf_0_0/design_2_util_ds_buf_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_util_ds_buf_0_0 || ORIG_REF_NAME==design_2_util_ds_buf_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_util_ds_buf_0_0/design_2_util_ds_buf_0_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_util_ds_buf_2_0/design_2_util_ds_buf_2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_util_ds_buf_2_0 || ORIG_REF_NAME==design_2_util_ds_buf_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_util_ds_buf_2_0/design_2_util_ds_buf_2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_util_ds_buf_2_0 || ORIG_REF_NAME==design_2_util_ds_buf_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_util_ds_buf_2_0/design_2_util_ds_buf_2_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_util_ds_buf_3_0/design_2_util_ds_buf_3_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_util_ds_buf_3_0 || ORIG_REF_NAME==design_2_util_ds_buf_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_util_ds_buf_3_0/design_2_util_ds_buf_3_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_util_ds_buf_3_0 || ORIG_REF_NAME==design_2_util_ds_buf_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_util_ds_buf_3_0/design_2_util_ds_buf_3_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_uartlite_0_0/design_2_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_axi_uartlite_0_0 || ORIG_REF_NAME==design_2_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_axi_uartlite_0_0/design_2_axi_uartlite_0_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_uartlite_0_0/design_2_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_axi_uartlite_0_0 || ORIG_REF_NAME==design_2_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_axi_gpio_0_0/design_2_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_axi_gpio_0_0 || ORIG_REF_NAME==design_2_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_axi_gpio_0_0/design_2_axi_gpio_0_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_gpio_0_0/design_2_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_axi_gpio_0_0 || ORIG_REF_NAME==design_2_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_clk_wiz_0_1/design_2_clk_wiz_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_0_1 || ORIG_REF_NAME==design_2_clk_wiz_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_clk_wiz_0_1/design_2_clk_wiz_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_0_1 || ORIG_REF_NAME==design_2_clk_wiz_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_clk_wiz_0_1/design_2_clk_wiz_0_1_ooc.xdc

# XDC: bd/design_2/ip/design_2_auto_pc_4/design_2_auto_pc_4_ooc.xdc

# XDC: bd/design_2/ip/design_2_auto_pc_3/design_2_auto_pc_3_ooc.xdc

# XDC: bd/design_2/ip/design_2_auto_pc_2/design_2_auto_pc_2_ooc.xdc

# XDC: bd/design_2/ip/design_2_auto_pc_1/design_2_auto_pc_1_ooc.xdc

# XDC: bd/design_2/ip/design_2_auto_pc_0/design_2_auto_pc_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_auto_pc_5/design_2_auto_pc_5_ooc.xdc

# XDC: bd/design_2/design_2_ooc.xdc
