# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/PDesign/PDesign.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PDesign || ORIG_REF_NAME==PDesign} -quiet] -quiet

# IP: bd/PDesign/ip/PDesign_processing_system7_0_0/PDesign_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PDesign_processing_system7_0_0 || ORIG_REF_NAME==PDesign_processing_system7_0_0} -quiet] -quiet

# IP: bd/PDesign/ip/PDesign_axi_uartlite_0_0/PDesign_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PDesign_axi_uartlite_0_0 || ORIG_REF_NAME==PDesign_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/PDesign/ip/PDesign_ps7_0_axi_periph_0/PDesign_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PDesign_ps7_0_axi_periph_0 || ORIG_REF_NAME==PDesign_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/PDesign/ip/PDesign_rst_ps7_0_100M_0/PDesign_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PDesign_rst_ps7_0_100M_0 || ORIG_REF_NAME==PDesign_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/PDesign/ip/PDesign_GPS_EN_0_0/PDesign_GPS_EN_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PDesign_GPS_EN_0_0 || ORIG_REF_NAME==PDesign_GPS_EN_0_0} -quiet] -quiet

# IP: bd/PDesign/ip/PDesign_axi_gpio_0_0/PDesign_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PDesign_axi_gpio_0_0 || ORIG_REF_NAME==PDesign_axi_gpio_0_0} -quiet] -quiet

# IP: bd/PDesign/ip/PDesign_xbar_0/PDesign_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PDesign_xbar_0 || ORIG_REF_NAME==PDesign_xbar_0} -quiet] -quiet

# IP: bd/PDesign/ip/PDesign_auto_pc_0/PDesign_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PDesign_auto_pc_0 || ORIG_REF_NAME==PDesign_auto_pc_0} -quiet] -quiet

# XDC: bd/PDesign/ip/PDesign_processing_system7_0_0/PDesign_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PDesign_processing_system7_0_0 || ORIG_REF_NAME==PDesign_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/PDesign/ip/PDesign_axi_uartlite_0_0/PDesign_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PDesign_axi_uartlite_0_0 || ORIG_REF_NAME==PDesign_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/PDesign/ip/PDesign_axi_uartlite_0_0/PDesign_axi_uartlite_0_0_ooc.xdc

# XDC: bd/PDesign/ip/PDesign_axi_uartlite_0_0/PDesign_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PDesign_axi_uartlite_0_0 || ORIG_REF_NAME==PDesign_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/PDesign/ip/PDesign_rst_ps7_0_100M_0/PDesign_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PDesign_rst_ps7_0_100M_0 || ORIG_REF_NAME==PDesign_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/PDesign/ip/PDesign_rst_ps7_0_100M_0/PDesign_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PDesign_rst_ps7_0_100M_0 || ORIG_REF_NAME==PDesign_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/PDesign/ip/PDesign_axi_gpio_0_0/PDesign_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PDesign_axi_gpio_0_0 || ORIG_REF_NAME==PDesign_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/PDesign/ip/PDesign_axi_gpio_0_0/PDesign_axi_gpio_0_0_ooc.xdc

# XDC: bd/PDesign/ip/PDesign_axi_gpio_0_0/PDesign_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PDesign_axi_gpio_0_0 || ORIG_REF_NAME==PDesign_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/PDesign/ip/PDesign_auto_pc_0/PDesign_auto_pc_0_ooc.xdc

# XDC: bd/PDesign/PDesign_ooc.xdc
