#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : design_2.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Mon Feb 18 13:16:07 -0600 2019
# SW Build 2258646 on Thu Jun 14 20:03:12 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved. 
#
# usage: design_2.sh [-help]
# usage: design_2.sh [-lib_map_path]
# usage: design_2.sh [-noclean_files]
# usage: design_2.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'design_2.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xil_defaultlib xpm fpgalib lib_cdc_v1_0_2 proc_sys_reset_v5_0_12 axi_infrastructure_v1_1_0 smartconnect_v1_0 axi_protocol_checker_v2_0_3 axi_vip_v1_1_3 processing_system7_vip_v1_0_5 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_17 fifo_generator_v13_2_2 axi_data_fifo_v2_1_16 axi_crossbar_v2_1_18 xlslice_v1_0_1 xlconcat_v2_1_1 xlconstant_v1_1_5 lib_pkg_v1_0_2 lib_fifo_v1_0_11 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_19 axi_sg_v4_1_10 axi_dma_v7_1_18 util_vector_logic_v2_0_1 axi_lite_ipif_v3_0_4 axi_uartlite_v2_0_21 interrupt_control_v3_1_4 axi_gpio_v2_0_19 axi_protocol_converter_v2_1_17)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "design_2.sh - Script generated by export_simulation (Vivado v2018.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "C:/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work FPGALIB $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ipshared/6737/src/mems_pkg.vhdl" \
    "$ref_dir/../../../bd/design_2/ipshared/6737/src/numeric_pkg.vhdl" \
    "$ref_dir/../../../bd/design_2/ipshared/6737/src/sync_pkg.vhdl" \
    "$ref_dir/../../../bd/design_2/ipshared/6737/src/FIFO.vhdl" \
    "$ref_dir/../../../bd/design_2/ipshared/6737/src/SimpleDualPortRAM.vhdl" \
    "$ref_dir/../../../bd/design_2/ipshared/6737/src/TrueDualPortRAM.vhdl" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ipshared/6737/hdl/comblock_v1_0_AXIL_REGS.vhd" \
    "$ref_dir/../../../bd/design_2/ipshared/6737/hdl/comblock_v1_0_AXIF_DRAM.vhd" \
    "$ref_dir/../../../bd/design_2/ipshared/6737/hdl/comblock_v1_0_AXIF_FIFO.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work FPGALIB $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ipshared/6737/src/ffchain.vhdl" \
    "$ref_dir/../../../bd/design_2/ipshared/6737/src/gray_sync.vhdl" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ipshared/6737/src/comblock.vhd" \
    "$ref_dir/../../../bd/design_2/ipshared/6737/hdl/comblock_v1_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_comblock_0_0/sim/design_2_comblock_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_12 $vhdlan_opts \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_proc_sys_reset_1_0/sim/design_2_proc_sys_reset_1_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_util_ds_buf_0_1/util_ds_buf.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_util_ds_buf_0_1/sim/design_2_util_ds_buf_0_1.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_util_ds_buf_1_0/sim/design_2_util_ds_buf_1_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_proc_sys_reset_0_0/sim/design_2_proc_sys_reset_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/sc_util_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_checker_v2_0_3 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/03a9/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_3 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b9a8/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_5 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ip/design_2_processing_system7_0_0/sim/design_2_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/6020/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/7aff/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_2 $vhdlan_opts \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/247d/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/15a3/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ip/design_2_xbar_0/sim/design_2_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ipshared/a1e0/Decimate_N.vhd" \
    "$ref_dir/../../../bd/design_2/ipshared/a1e0/Decimate_by2.vhd" \
    "$ref_dir/../../../bd/design_2/ipshared/a1e0/ADC_Decimator.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_ADC_Decimator_0_0/sim/design_2_ADC_Decimator_0_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_DAC_CTRL1v1_0_0/sim/design_2_DAC_CTRL1v1_0_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_Hist_Gen_Block_0_0/ipshared/b9df/src/histo_counter.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_Hist_Gen_Block_0_0/src/Histo1_histo_counter_0_0/sim/Histo1_histo_counter_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlslice_v1_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ip/design_2_Hist_Gen_Block_0_0/ipshared/f3db/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ip/design_2_Hist_Gen_Block_0_0/src/Histo1_xlslice_0_0/sim/Histo1_xlslice_0_0.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_Hist_Gen_Block_0_0/src/Histo1_xlslice_0_1/sim/Histo1_xlslice_0_1.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_Hist_Gen_Block_0_0/src/Histo1_reg_bit_1_0/sim/Histo1_reg_bit_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_Hist_Gen_Block_0_0/ipshared/2902/src/Top.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_Hist_Gen_Block_0_0/src/Histo1_SBRAM_wen_mgr_0_0/sim/Histo1_SBRAM_wen_mgr_0_0.vhd" \
    "$ref_dir/../../../bd/design_2/ipshared/88e5/src/Histo1.vhd" \
    "$ref_dir/../../../bd/design_2/ipshared/88e5/src/Histo1_wrapper.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_Hist_Gen_Block_0_0/sim/design_2_Hist_Gen_Block_0_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_FIFOMGR_0_0/sim/design_2_FIFOMGR_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ip/design_2_ctrl_reg_0/sim/design_2_ctrl_reg_0.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_ctrl_reg1_0/sim/design_2_ctrl_reg1_0.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_ctrl_reg2_0/sim/design_2_ctrl_reg2_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_mstrigger_0_0/sim/design_2_mstrigger_0_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_timer_0_0/sim/design_2_timer_0_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_timestamp_1_0/sim/design_2_timestamp_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ip/design_2_xlconcat_0_1/sim/design_2_xlconcat_0_1.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_xlconcat_1_0/sim/design_2_xlconcat_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ipshared/01f9/sources_1/imports/axi_trigger_gen_m3_v1_0/new/Trigger_m4.vhd" \
    "$ref_dir/../../../bd/design_2/ipshared/01f9/sources_1/imports/axi_trigger_gen_m3_v1_0/imports/hdl/AXI_Trigger_gen_m4_v1_0_S00_AXI.vhd" \
    "$ref_dir/../../../bd/design_2/ipshared/01f9/sources_1/imports/axi_trigger_gen_m3_v1_0/imports/hdl/AXI_Trigger_gen_m4_v1_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_AXI_Trigger_gen_m4_0_0/sim/design_2_AXI_Trigger_gen_m4_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconstant_v1_1_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f1c3/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ip/design_2_FIFO_SIZE_0/sim/design_2_FIFO_SIZE_0.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_OLD_fifo_0/sim/design_2_OLD_fifo_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_fifo_v1_0_11 $vhdlan_opts \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/6078/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_19 $vhdlan_opts \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec8a/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_sg_v4_1_10 $vhdlan_opts \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/6e5f/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_18 $vhdlan_opts \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/6bfe/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_axi_dma_0_0/sim/design_2_axi_dma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ip/design_2_axi_smc_0/bd_0/sim/bd_ebcc.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5160/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_7/sim/bd_ebcc_s00a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/acc2/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_11/sim/bd_ebcc_m00s2a_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/28cb/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_12/sim/bd_ebcc_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_8/sim/bd_ebcc_sawn_0.sv" \
    "$ref_dir/../../../bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_9/sim/bd_ebcc_swn_0.sv" \
    "$ref_dir/../../../bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_10/sim/bd_ebcc_sbn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/afa8/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_4/sim/bd_ebcc_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/4521/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_5/sim/bd_ebcc_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/d1fc/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_6/sim/bd_ebcc_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_0/sim/bd_ebcc_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_1/sim/bd_ebcc_psr0_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_2/sim/bd_ebcc_psr_aclk_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_axi_smc_0/bd_0/ip/ip_3/sim/bd_ebcc_psr_aclk1_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_axi_smc_0/sim/design_2_axi_smc_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/2137/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ip/design_2_empty_0/sim/design_2_empty_0.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_full_0/sim/design_2_full_0.v" \
    "$ref_dir/../../../bd/design_2/ipshared/9ce3/tlast_gen.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_tlast_gen_0_0/sim/design_2_tlast_gen_0_0.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_xlconcat_0_0/sim/design_2_xlconcat_0_0.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_xlconstant_0_0/sim/design_2_xlconstant_0_0.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_xlconstant_1_0/sim/design_2_xlconstant_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_adc_controller_0_0/sim/design_2_adc_controller_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ip/design_2_clk_wiz_0_0/design_2_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_clk_wiz_0_0/design_2_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_util_ds_buf_0_0/sim/design_2_util_ds_buf_0_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_util_ds_buf_2_0/sim/design_2_util_ds_buf_2_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_util_ds_buf_3_0/sim/design_2_util_ds_buf_3_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/cced/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_uartlite_v2_0_21 $vhdlan_opts \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/a15e/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_axi_uartlite_0_0/sim/design_2_axi_uartlite_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/8e66/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_19 $vhdlan_opts \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/c193/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_2/ip/design_2_axi_gpio_0_0/sim/design_2_axi_gpio_0_0.vhd" \
    "$ref_dir/../../../bd/design_2/ip/design_2_GPS_EN_0_0/sim/design_2_GPS_EN_0_0.vhd" \
    "$ref_dir/../../../bd/design_2/sim/design_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ip/design_2_clk_wiz_0_1/design_2_clk_wiz_0_1_clk_wiz.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_clk_wiz_0_1/design_2_clk_wiz_0_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ccfb/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/70fd/hdl" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/f90c/hdl/verilog" +incdir+"$ref_dir/../../../../LAGO_ICTP.srcs/sources_1/bd/design_2/ipshared/b65a" +incdir+"C:/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_2/ip/design_2_auto_pc_4/sim/design_2_auto_pc_4.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_auto_pc_3/sim/design_2_auto_pc_3.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_auto_pc_2/sim/design_2_auto_pc_2.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_auto_pc_1/sim/design_2_auto_pc_1.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_auto_pc_0/sim/design_2_auto_pc_0.v" \
    "$ref_dir/../../../bd/design_2/ip/design_2_auto_pc_5/sim/design_2_auto_pc_5.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.design_2 xil_defaultlib.glbl -o design_2_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./design_2_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./design_2.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key design_2_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc design_2_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./design_2.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: design_2.sh [-help]\n\
Usage: design_2.sh [-lib_map_path]\n\
Usage: design_2.sh [-reset_run]\n\
Usage: design_2.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
